
CREATE PROCEDURE [dbo].[USP_CreateStates] 
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from interfering with SELECT statements.
	SET NOCOUNT ON;

	DELETE FROM dbo.State

	INSERT INTO dbo.State (StateCode,StateName) VALUES ( 'AK','ALASKA')
	INSERT INTO dbo.State (StateCode,StateName) VALUES ( 'AL','ALABAMA')
	INSERT INTO dbo.State (StateCode,StateName) VALUES ( 'AR','ARKANSAS')
	INSERT INTO dbo.State (StateCode,StateName) VALUES ( 'AZ','ARIZONA')
	INSERT INTO dbo.State (StateCode,StateName) VALUES ( 'CA','CALIFORNIA')
	INSERT INTO dbo.State (StateCode,StateName) VALUES ( 'CO','COLORADO')
	INSERT INTO dbo.State (StateCode,StateName) VALUES ( 'CT','CONNECTICUT')
	INSERT INTO dbo.State (StateCode,StateName) VALUES ( 'DE','DELAWARE')
	INSERT INTO dbo.State (StateCode,StateName) VALUES ( 'FL','FLORIDA')
	INSERT INTO dbo.State (StateCode,StateName) VALUES ( 'GA','GEORGIA')
	INSERT INTO dbo.State (StateCode,StateName) VALUES ( 'HI','HAWAII')
	INSERT INTO dbo.State (StateCode,StateName) VALUES ( 'IA','IOWA')
	INSERT INTO dbo.State (StateCode,StateName) VALUES ( 'ID','IDAHO')
	INSERT INTO dbo.State (StateCode,StateName) VALUES ( 'IL','ILLINOIS')
	INSERT INTO dbo.State (StateCode,StateName) VALUES ( 'IN','INDIANA')
	INSERT INTO dbo.State (StateCode,StateName) VALUES ( 'KS','KANSAS')
	INSERT INTO dbo.State (StateCode,StateName) VALUES ( 'KY','KENTUCKY')
	INSERT INTO dbo.State (StateCode,StateName) VALUES ( 'LA','LOUISIANA')
	INSERT INTO dbo.State (StateCode,StateName) VALUES ( 'MA','MASSACHUSETTS')
	INSERT INTO dbo.State (StateCode,StateName) VALUES ( 'MD','MARYLAND')
	INSERT INTO dbo.State (StateCode,StateName) VALUES ( 'ME','MAINE')
	INSERT INTO dbo.State (StateCode,StateName) VALUES ( 'MI','MICHIGAN')
	INSERT INTO dbo.State (StateCode,StateName) VALUES ( 'MN','MINNESOTA')
	INSERT INTO dbo.State (StateCode,StateName) VALUES ( 'MO','MISSOURI')
	INSERT INTO dbo.State (StateCode,StateName) VALUES ( 'MS','MISSISSIPPI')
	INSERT INTO dbo.State (StateCode,StateName) VALUES ( 'MT','MONTANA')
	INSERT INTO dbo.State (StateCode,StateName) VALUES ( 'NC','NORTH CAROLINA')
	INSERT INTO dbo.State (StateCode,StateName) VALUES ( 'ND','NORTH DAKOTA')
	INSERT INTO dbo.State (StateCode,StateName) VALUES ( 'NE','NEBRASKA')
	INSERT INTO dbo.State (StateCode,StateName) VALUES ( 'NH','NEW HAMPSHIRE')
	INSERT INTO dbo.State (StateCode,StateName) VALUES ( 'NJ','NEW JERSEY')
	INSERT INTO dbo.State (StateCode,StateName) VALUES ( 'NM','NEW MEXICO')
	INSERT INTO dbo.State (StateCode,StateName) VALUES ( 'NV','NEVADA')
	INSERT INTO dbo.State (StateCode,StateName) VALUES ( 'NY','NEW YORK')
	INSERT INTO dbo.State (StateCode,StateName) VALUES ( 'OH','OHIO')
	INSERT INTO dbo.State (StateCode,StateName) VALUES ( 'OK','OKLAHOMA')
	INSERT INTO dbo.State (StateCode,StateName) VALUES ( 'OR','OREGON')
	INSERT INTO dbo.State (StateCode,StateName) VALUES ( 'PA','PENNSYLVANIA')
	INSERT INTO dbo.State (StateCode,StateName) VALUES ( 'RI','RHODE ISLAND')
	INSERT INTO dbo.State (StateCode,StateName) VALUES ( 'SC','SOUTH CAROLINA')
	INSERT INTO dbo.State (StateCode,StateName) VALUES ( 'SD','SOUTH DAKOTA')
	INSERT INTO dbo.State (StateCode,StateName) VALUES ( 'TN','TENNESSEE')
	INSERT INTO dbo.State (StateCode,StateName) VALUES ( 'TX','TEXAS')
	INSERT INTO dbo.State (StateCode,StateName) VALUES ( 'UT','UTAH')
	INSERT INTO dbo.State (StateCode,StateName) VALUES ( 'VA','VIRGINIA')
	INSERT INTO dbo.State (StateCode,StateName) VALUES ( 'VT','VERMONT')
	INSERT INTO dbo.State (StateCode,StateName) VALUES ( 'WA','WASHINGTON')
	INSERT INTO dbo.State (StateCode,StateName) VALUES ( 'WI','WISCONSIN')
	INSERT INTO dbo.State (StateCode,StateName) VALUES ( 'WV','WEST VIRGINIA')
	INSERT INTO dbo.State (StateCode,StateName) VALUES ( 'WY','WYOMING')
END